import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import React, {ReactNode} from 'react';
import {Footer} from '@/components/Footer';
import {Header} from '@/components/Header';
import {AuthProvider} from '@/providers/authProvider';

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <AuthProvider>
            <Header/>
            <main className="container">
                {children}
            </main>
            <Footer/>
        </AuthProvider>
        </body>
        </html>
    )
}
